./do_QUfit_1D_auto.py data_simple/Source1.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source2.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source3.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source4.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source5.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source6.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source7.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source8.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source9.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source10.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source11.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source12.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source13.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source14.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source15.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source16.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source17.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source18.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source19.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source20.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source21.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source22.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source23.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source24.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source25.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source26.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source27.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source28.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source29.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source30.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source31.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source32.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source33.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source34.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source35.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source36.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source37.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source38.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source39.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source40.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source41.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source42.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source43.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source44.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source45.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source46.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source47.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source48.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source49.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source50.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source51.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source52.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source53.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source54.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source55.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source56.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source57.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source58.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source59.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source60.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source61.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source62.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source63.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source64.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source65.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source66.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source67.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source68.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source69.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source70.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source71.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source72.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source73.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source74.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source75.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source76.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source77.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source78.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source79.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source80.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source81.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source82.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source83.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source84.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source85.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source86.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source87.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source88.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source89.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source90.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source91.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source92.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source93.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source94.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source95.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source96.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source97.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source98.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source99.dat -t 3 -m 1
./do_QUfit_1D_auto.py data_simple/Source100.dat -t 3 -m 1
